### PR TITLE
Fix invalid type in ServiceProviders

### PR DESCRIPTION
**Pull request by szepeviktor**
props. @phpstan

### CODE REVIEW

**Comment by gmazzap** [comment]
Sorry @szepeviktor, that is a perfectly valid type in Psalm (which has a more powerful type system than PHPStan).

See how thanks to that annotation Psalm can find wrong types attached to a `SplStorage:` https://psalm.dev/r/aae4b7470c

**Comment by szepeviktor** [comment]
Okay.
Suspected.

**Comment by ondrejmirtes** [comment]
PHPStan has a generic stub for SplObjectStorage compatible with Psalm's so don't know what the issue here is: https://github.com/phpstan/phpstan-src/blob/master/stubs/SplObjectStorage.stub

**Comment by ondrejmirtes** [comment]
Oh, I just noticed the SplObjectStorage stub wasn't registered, fixed: https://github.com/phpstan/phpstan-src/commit/143741c9c68edcc96845926b551d40eeed2af0d5

**Comment by szepeviktor** [comment]
@ondrejmirtes Thank you.

**Comment by gmazzap** [comment]
Thanks for explaination @ondrejmirtes I guess it's a while I don't use PHPStan.

Can I ask you a question? The type system compatible with Psalm, is a separate implementation or you're using Psalm type system implementation somehow?

**Comment by ondrejmirtes** [comment]
Psalm and PHPStan don't share any implementation details. To check out how PHPStan's typesystem is implemented, see: https://github.com/phpstan/phpstan-src/tree/master/src/Type

**Pull request closed without merging**
